// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtOUXy6cmKa51c5udLWnQxebE1AJ7qm9A',
    appId: '1:9542344535:web:3fd16e5a8847ca3d15e812',
    messagingSenderId: '9542344535',
    projectId: 'note-app-ff981',
    authDomain: 'note-app-ff981.firebaseapp.com',
    storageBucket: 'note-app-ff981.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdOphbBWSTNvIF5p6iiQzSTsNy6uSpb70',
    appId: '1:9542344535:android:78d320c039a8870215e812',
    messagingSenderId: '9542344535',
    projectId: 'note-app-ff981',
    storageBucket: 'note-app-ff981.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtOUXy6cmKa51c5udLWnQxebE1AJ7qm9A',
    appId: '1:9542344535:web:0f88dd07664832dc15e812',
    messagingSenderId: '9542344535',
    projectId: 'note-app-ff981',
    authDomain: 'note-app-ff981.firebaseapp.com',
    storageBucket: 'note-app-ff981.firebasestorage.app',
  );
}
